apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm-guestbook
    repoURL: "https://github.com/mehoussou/argocd-example-apps.git"
    targetRevision: argo-test-branch
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
